# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0625cf324771138322d330870a14f2182a8c8fd9a83efbc56c6779de67935c4bf1d5590592d72f48c2440d2acfcf5530b512ae6dc540959eea464acdb7be8f4e

test:
  secret_key_base: 5f53741f121e954d851306027ca19beb0cdd42f4676241425080a7a9e246e868c169a955a308cf17bb92eccf21df7a7aa0bbbacf5ecc29ae0cf1b683490193a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
